AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: provided.al2023
    Handler: bootstrap
    Architectures:
      - x86_64

Resources:
  SimpleChatWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SimpleChatWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SimpleChatWebSocket
      RouteKey: $connect
      Target: !Sub 'integrations/${ConnectIntegration}'

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SimpleChatWebSocket
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyWebsocketFunction.Arn}/invocations'

  WebSocketDeploy:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref SimpleChatWebSocket

  WebSocketTestStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref SimpleChatWebSocket
      DeploymentId: !Ref WebSocketDeploy
      StageName: Prod

  MyWebsocketFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/my-ws/
      Policies:
        - DynamoDBCrudPolicy: 
            TableName: !Ref StateDynamoDB
      Environment:
        Variables:
          STATEDYNAMODB: !Ref StateDynamoDB

  GameMoveFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/game-move/
      Policies:
        - DynamoDBCrudPolicy: 
            TableName: !Ref StateDynamoDB
      Environment:
        Variables:
          STATEDYNAMODB: !Ref StateDynamoDB
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /move
            Method: GET

  StateDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

# Outputs:
