package vars

import "os"

const (
	JOINEVENT  = "JOIN"
	LEAVEEVENT = "LEAVE"
	CHATEVENT  = "CHAT"
	GAMEEVENT  = "GAME"
	USEREVENT  = "USER"
	SLOTEVENT  = "SLOT"

	INFOEVENT = "INFO"

	GLOBALCHAT = "GLOBAL"
)

var (
	GAME_TABLE_DYNAMODB   = os.Getenv("GAME_TABLE_DYNAMODB")
	USER_DYNAMODB         = os.Getenv("USER_DYNAMODB")
	CONNECTION_DYNAMODB   = os.Getenv("CONNECTION_DYNAMODB")
	WEBSOCKET_EVENT_QUEUE = os.Getenv("WEBSOCKET_EVENT_QUEUE")
	WEB_CLIENT_ORIGIN     = os.Getenv("WEB_CLIENT_ORIGIN")
	WEBSOCKET_ENDPOINT    = os.Getenv("WEBSOCKET_ENDPOINT")
)
